apiVersion: v1
kind: Service
metadata:
    name: "abodit-6b58"
    labels:
        app: "abodit-6b58"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "abodit-6b58"