on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: abodit.azurecr.io
        username: ${{ secrets.acr_abodit_username }}
        password: ${{ secrets.acr_abodit_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t abodit.azurecr.io/abodit:${{ github.sha }}
        docker push abodit.azurecr.io/abodit:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_abodit_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep abodita1e1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace abodita1e1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: abodita1e1
        container-registry-url: abodit.azurecr.io
        container-registry-username: ${{ secrets.acr_abodit_username }}
        container-registry-password: ${{ secrets.acr_abodit_password }}
        secret-name: aboditdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: abodita1e1
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          abodit.azurecr.io/abodit:${{ github.sha }}
        imagepullsecrets: |
          aboditdockerauth